'use client';

import { useRef, useState } from 'react';
import Image from 'next/image';
import { motion, AnimatePresence, useInView } from 'framer-motion';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';

/**
 * What a message turns into.
 *
 * Everything here is REAL, which is the point of the section:
 *  - the image is genuinely MODUS output (public/made-by-modus.png, generated by
 *    gpt-image-1 through the same path /api/generate/image uses) and the prompt
 *    shown is the prompt that made it;
 *  - the chart is a live recharts render, the same library ChartCard renders in
 *    chat — not a picture of a chart.
 * If you add a card here, it must be something chat actually emits today:
 * approval | draft_options | options | image | document | chart. Anything else
 * is a promise. The modes plan (Gamma-style decks, Cal AI-style logging) has no
 * renderer yet, so it does NOT belong on this page.
 */

const CHART_DATA = [
  { label: 'Mon', Deep: 3.5, Meetings: 1.0 },
  { label: 'Tue', Deep: 2.0, Meetings: 3.5 },
  { label: 'Wed', Deep: 4.5, Meetings: 0.5 },
  { label: 'Thu', Deep: 1.5, Meetings: 4.0 },
  { label: 'Fri', Deep: 5.0, Meetings: 1.0 },
];

const TABS = [
  { id: 'image', label: 'An image', ask: 'Generate an image of a lone climber at dawn' },
  { id: 'chart', label: 'A chart', ask: 'Chart my deep work vs meetings this week' },
  { id: 'doc', label: 'A document', ask: 'Turn my Q3 notes into a PDF I can send' },
] as const;

function ImageCard() {
  return (
    <div className="rounded-xl overflow-hidden bg-bg ring-1 ring-text/[0.06]">
      {/* Capped: the source is square, and at this container's width an
          unconstrained 1024x1024 is ~1000px tall — it swallowed the section and
          made the tab strip jump when switching to the shorter chart/doc. */}
      <div className="relative h-[300px] sm:h-[340px]">
        <Image
          src="/made-by-modus.png"
          alt="A lone climber on a dark granite ridge at dawn, generated by MODUS"
          fill
          sizes="(max-width: 1024px) 100vw, 960px"
          className="object-cover object-center"
        />
      </div>
      <p className="px-4 py-3 text-[11px] text-muted/70 leading-relaxed">
        Actually made by MODUS, from that prompt. Not a stock photo.
      </p>
    </div>
  );
}

function ChartPreview() {
  return (
    <div className="rounded-xl bg-bg ring-1 ring-text/[0.06] p-4">
      <div className="flex items-center justify-between gap-3 mb-3">
        <p className="text-xs font-semibold text-text">Deep work vs meetings · hours</p>
        {/* Without this the two lines are just "purple" and "dashed purple" —
            unreadable unless you hover a tooltip, which nobody does on a
            marketing page. */}
        <div className="flex items-center gap-3 shrink-0">
          <span className="flex items-center gap-1.5 text-[10px] text-muted">
            <span className="w-4 h-0.5 rounded-full bg-[#7C3AED]" /> Deep work
          </span>
          <span className="flex items-center gap-1.5 text-[10px] text-muted">
            <span className="w-4 border-t-2 border-dashed border-[#a78bfa]" /> Meetings
          </span>
        </div>
      </div>
      <div className="h-[260px]">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={CHART_DATA} margin={{ top: 4, right: 8, bottom: 0, left: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
            <XAxis dataKey="label" tick={{ fill: 'rgb(140,140,148)', fontSize: 11 }} axisLine={false} tickLine={false} />
            <YAxis width={28} tick={{ fill: 'rgb(140,140,148)', fontSize: 11 }} axisLine={false} tickLine={false} />
            <Tooltip
              contentStyle={{ background: 'rgb(22,22,24)', border: '1px solid rgb(32,32,35)', borderRadius: 10, fontSize: 12 }}
              labelStyle={{ color: 'rgb(237,237,240)' }}
            />
            <Line type="monotone" dataKey="Deep" stroke="#7C3AED" strokeWidth={2.5} dot={{ r: 3 }} />
            <Line type="monotone" dataKey="Meetings" stroke="#a78bfa" strokeWidth={2} strokeDasharray="4 4" dot={{ r: 3 }} />
          </LineChart>
        </ResponsiveContainer>
      </div>
      <p className="text-[11px] text-muted/70 mt-2">A live chart, not a screenshot. Same renderer you get in chat.</p>
    </div>
  );
}

function DocPreview() {
  return (
    <div className="rounded-xl bg-bg ring-1 ring-text/[0.06] p-4">
      <div className="flex items-center gap-3 px-3 py-3 rounded-lg bg-panel ring-1 ring-text/[0.06]">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.6} className="w-6 h-6 text-brand shrink-0">
          <path strokeLinecap="round" strokeLinejoin="round" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
          <path strokeLinecap="round" strokeLinejoin="round" d="M14 2v6h6" />
        </svg>
        <span className="min-w-0 flex-1">
          <span className="block text-sm font-semibold text-text truncate">Q3-review.pdf</span>
          <span className="block text-[11px] text-muted">Ready to download</span>
        </span>
        <span className="text-xs font-semibold text-brand shrink-0">Download</span>
      </div>
      <div className="mt-4 space-y-2 px-1">
        {['Q3 Review', 'Revenue grew 34% against a flat headcount.', 'Churn fell to 2.1%, the lowest this year.', 'Biggest risk: onboarding still takes 9 days.'].map((line, i) => (
          <div key={line} className={i === 0 ? 'text-sm font-bold text-text' : 'text-xs text-muted leading-relaxed'}>{line}</div>
        ))}
      </div>
      <p className="text-[11px] text-muted/70 mt-4">Written, formatted and handed back as a real file.</p>
    </div>
  );
}

export default function CreationsSection() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-80px 0px' });
  const [tab, setTab] = useState<(typeof TABS)[number]['id']>('image');
  const active = TABS.find(t => t.id === tab)!;

  return (
    <section className="px-6 py-20 max-w-5xl mx-auto" ref={ref}>
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={inView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      >
        <p className="text-xs font-bold text-brand dark:text-brand-light uppercase tracking-widest mb-3">What it makes</p>
        <h2 className="text-4xl md:text-5xl font-semibold text-text mb-4 tracking-tight">
          It doesn&apos;t describe things.<br />
          <span className="text-brand dark:text-brand-light">It makes them.</span>
        </h2>
        <p className="text-muted text-lg leading-relaxed max-w-2xl mb-8">
          Ask in the same chat that reads your calendar. The answer comes back as the actual thing, not a paragraph telling you how to go make it.
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={inView ? { opacity: 1, y: 0 } : {}}
        transition={{ delay: 0.12, duration: 0.45, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="flex flex-wrap gap-2 mb-5">
          {TABS.map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`relative px-4 py-2 rounded-xl text-sm font-medium transition-colors ${
                tab === t.id ? 'text-white' : 'bg-panel text-muted hover:text-text'
              }`}
            >
              {tab === t.id && (
                <motion.span layoutId="creationTab" transition={{ type: 'spring', stiffness: 420, damping: 34 }} className="absolute inset-0 bg-brand rounded-xl" />
              )}
              <span className="relative z-10">{t.label}</span>
            </button>
          ))}
        </div>

        <div className="bg-panel rounded-2xl p-4 shadow-2xl shadow-black/30">
          {/* The ask, as a real chat turn */}
          <div className="flex justify-end mb-4">
            <div className="bg-brand text-white rounded-2xl rounded-br-sm px-4 py-2.5 max-w-[80%]">
              <p className="text-sm leading-relaxed">{active.ask}</p>
            </div>
          </div>
          <AnimatePresence mode="wait">
            <motion.div
              key={tab}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.2 }}
            >
              {tab === 'image' ? <ImageCard /> : tab === 'chart' ? <ChartPreview /> : <DocPreview />}
            </motion.div>
          </AnimatePresence>
        </div>
      </motion.div>
    </section>
  );
}
